name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  format:
    if: github.repository_owner == 'astrolicious'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/create-github-app-token@v1.9.3
        id: app-token
        with:
          app-id: ${{ vars.BOT_APPID }}
          private-key: ${{ secrets.BOT_SECRET }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint code with Biome
        run: pnpm run lint:fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[ci] lint"
          branch: ${{ github.head_ref }}
